name: .NET Core Desktop

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: dotnet-tac
      Test_Project_Path: TACBuilder.UnitTests\TACBuilder.UnitTests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Build TACBuilder.UnitTests
      run: dotnet build 'TACBuilder.UnitTests\TACBuilder.UnitTests.csproj' -c Release

    - name: Execute unit tests
      run: dotnet test
